### deployment.yaml ###
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets
  namespace: argocd
  labels:
    app: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      name: vets-petclinic-tem
      labels:
        app: spring-petclinic
    spec:
      containers:
      - name: vets
        image: asia-northeast3-docker.pkg.dev/hyunyoung-01-368306/gcpzg/spring-petclinic-vets-service:latest
        ports:
        - containerPort: 8080

---
### service.yaml ###
---
apiVersion: v1
kind: Service
metadata:
  name: vets
  namespace: argocd
spec:
  selector:
    app: spring-petclinic
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
